### ISSUE TITLE
ClusterCrash #88

### ISSUE THREAD

**Issue by jaxx56** [mangosvb/serverZero#104]
[09:38:12] [000001] Client Transfer Map 001 to Map 000
[09:38:17]  MSG_MOVE_WORLDPORT_ACK
[09:38:18] [000001] Client chat flag update [0x3]
[09:38:20]  CMSG_JOIN_CHANNEL [GuildRecruitment - City]
[09:38:20]  CMSG_REQUEST_RAID_INFO
[09:38:20]  CMSG_GMTICKET_GETTICKET
[09:38:20]  CMSG_QUERY_TIME
[09:38:20]  SMSG_QUERY_TIME_RESPONSE
[09:38:20]  CMSG_MOVE_TIME_SKIPPED
[09:38:21]  BAD PACKET 13(18) bytes,
[09:38:21]  BAD PACKET 82(62722) bytes,
[09:38:21]  BAD PACKET 399(39847) bytes,
[09:38:21] System.IndexOutOfRangeException: Index was outside the bounds of the
array.
   at WorldCluster.WC_Network.ClientClass.OnPacket(Object state) in C:\Users\Kri
ll\Desktop\MVB\src\Server\WorldCluster\Server\WC.Network.vb:line 655
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object sta
te)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[09:38:21] Unexpected error has occured. An 'Error-yyyy-mmm-d-h-mm.log' file has
 been created. Please post the file in the HELP SECTION at getMangos.com (http:/
/www.getMangos.co.uk)!

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the boun
ds of the array.
   at WorldCluster.WC_Network.ClientClass.OnPacket(Object state) in C:\Users\Kri
ll\Desktop\MVB\src\Server\WorldCluster\Server\WC.Network.vb:line 655
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object sta
te)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
[09:38:21]  BAD PACKET 8(23745) bytes,
[09:38:21]  BAD PACKET 74(64756) bytes,
[09:38:21]  BAD PACKET 29(20544) bytes,
[09:38:21]  BAD PACKET 64(26624) bytes,
[09:38:22]  BAD PACKET 32(64717) bytes,
[09:38:22]  BAD PACKET 32(13113) bytes,

**Comment by Krilliac** [comment]
https://github.com/mangosvb/serverZero/commit/749092eacab1d5bccd80bf3c776c215967d1a93d fixes this, closing.
