### ISSUE TITLE
Opcode Handler CMSG_ITEM_QUERY_SINGLE Error

### ISSUE THREAD

**Issue by jaxx56** [mangosvb/serverZero#108]
Might be related to #107 

Opcode handler CMSG_ITEM_QUERY_SINGLE:CMSG_ITEM_QUERY_SINGLE caused a
n error:
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at MySql.Data.MySqlClient.NativeDriver.ExecuteCommand(DBCmd cmd, Byte[] bytes
, Int32 length)
   at MySql.Data.MySqlClient.NativeDriver.Query(Byte[] bytes, Int32 length)
   at MySql.Data.MySqlClient.Statement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior
)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior be
havior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandB
ehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[]
 datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand co
mmand, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startR
ecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at mangosVB.Common.SQL.Query(String sqlquery, DataTable& Result) in C:\Users\
Krill\Desktop\MVB\src\Server\Common\SQL.vb:line 390
   at mangosVB.WorldServer.WS_Items.ItemInfo..ctor(Int32 itemId) in C:\Users\Kri
ll\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:line 75
   at mangosVB.WorldServer.WS_Items.SendItemInfo(ClientClass& client, Int32 item
ID) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:lin
e 534
   at mangosVB.WorldServer.WS_Items.On_CMSG_ITEM_QUERY_SINGLE(PacketClass& packe
t, ClientClass& client) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Obj
ects\WS.Items.vb:line 646
   at mangosVB.WorldServer.WS_Network.ClientClass.OnPacket(Object state) in C:\U
sers\Krill\Desktop\MVB\src\Server\WorldServer\Server\WS.Network.vb:line 387
[10:23:18] Opcode handler CMSG_ITEM_QUERY_SINGLE:CMSG_ITEM_QUERY_SINGLE caused a
n error:
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at MySql.Data.MySqlClient.NativeDriver.ExecuteCommand(DBCmd cmd, Byte[] bytes
, Int32 length)
   at MySql.Data.MySqlClient.NativeDriver.Query(Byte[] bytes, Int32 length)
   at MySql.Data.MySqlClient.Statement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior
)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior be
havior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandB
ehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[]
 datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand co
mmand, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startR
ecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at mangosVB.Common.SQL.Query(String sqlquery, DataTable& Result) in C:\Users\
Krill\Desktop\MVB\src\Server\Common\SQL.vb:line 390
   at mangosVB.WorldServer.WS_Items.ItemInfo..ctor(Int32 itemId) in C:\Users\Kri
ll\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:line 75
   at mangosVB.WorldServer.WS_Items.SendItemInfo(ClientClass& client, Int32 item
ID) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:lin
e 534
   at mangosVB.WorldServer.WS_Items.On_CMSG_ITEM_QUERY_SINGLE(PacketClass& packe
t, ClientClass& client) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Obj
ects\WS.Items.vb:line 646
   at mangosVB.WorldServer.WS_Network.ClientClass.OnPacket(Object state) in C:\U
sers\Krill\Desktop\MVB\src\Server\WorldServer\Server\WS.Network.vb:line 387
[10:23:18] Opcode handler CMSG_ITEM_QUERY_SINGLE:CMSG_ITEM_QUERY_SINGLE caused a
n error:
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at MySql.Data.MySqlClient.NativeDriver.ExecuteCommand(DBCmd cmd, Byte[] bytes
, Int32 length)
   at MySql.Data.MySqlClient.NativeDriver.Query(Byte[] bytes, Int32 length)
   at MySql.Data.MySqlClient.Statement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior
)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior be
havior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandB
ehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[]
 datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand co
mmand, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startR
ecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at mangosVB.Common.SQL.Query(String sqlquery, DataTable& Result) in C:\Users\
Krill\Desktop\MVB\src\Server\Common\SQL.vb:line 390
   at mangosVB.WorldServer.WS_Items.ItemInfo..ctor(Int32 itemId) in C:\Users\Kri
ll\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:line 75
   at mangosVB.WorldServer.WS_Items.SendItemInfo(ClientClass& client, Int32 item
ID) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:lin
e 534
   at mangosVB.WorldServer.WS_Items.On_CMSG_ITEM_QUERY_SINGLE(PacketClass& packe
t, ClientClass& client) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Obj
ects\WS.Items.vb:line 646
   at mangosVB.WorldServer.WS_Network.ClientClass.OnPacket(Object state) in C:\U
sers\Krill\Desktop\MVB\src\Server\WorldServer\Server\WS.Network.vb:line 387
[10:23:18] Opcode handler CMSG_ITEM_QUERY_SINGLE:CMSG_ITEM_QUERY_SINGLE caused a
n error:
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at MySql.Data.MySqlClient.NativeDriver.ExecuteCommand(DBCmd cmd, Byte[] bytes
, Int32 length)
   at MySql.Data.MySqlClient.NativeDriver.Query(Byte[] bytes, Int32 length)
   at MySql.Data.MySqlClient.Statement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior
)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior be
havior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandB
ehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[]
 datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand co
mmand, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startR
ecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at mangosVB.Common.SQL.Query(String sqlquery, DataTable& Result) in C:\Users\
Krill\Desktop\MVB\src\Server\Common\SQL.vb:line 390
   at mangosVB.WorldServer.WS_Items.ItemInfo..ctor(Int32 itemId) in C:\Users\Kri
ll\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:line 75
   at mangosVB.WorldServer.WS_Items.SendItemInfo(ClientClass& client, Int32 item
ID) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:lin
e 534
   at mangosVB.WorldServer.WS_Items.On_CMSG_ITEM_QUERY_SINGLE(PacketClass& packe
t, ClientClass& client) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Obj
ects\WS.Items.vb:line 646
   at mangosVB.WorldServer.WS_Network.ClientClass.OnPacket(Object state) in C:\U
sers\Krill\Desktop\MVB\src\Server\WorldServer\Server\WS.Network.vb:line 387
[10:23:18] Opcode handler CMSG_ITEM_QUERY_SINGLE:CMSG_ITEM_QUERY_SINGLE caused a
n error:
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at MySql.Data.MySqlClient.NativeDriver.ExecuteCommand(DBCmd cmd, Byte[] bytes
, Int32 length)
   at MySql.Data.MySqlClient.NativeDriver.Query(Byte[] bytes, Int32 length)
   at MySql.Data.MySqlClient.Statement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.ExecuteNext()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior
)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior be
havior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandB
ehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[]
 datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand co
mmand, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startR
ecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at mangosVB.Common.SQL.Query(String sqlquery, DataTable& Result) in C:\Users\
Krill\Desktop\MVB\src\Server\Common\SQL.vb:line 390
   at mangosVB.WorldServer.WS_Items.ItemInfo..ctor(Int32 itemId) in C:\Users\Kri
ll\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:line 75
   at mangosVB.WorldServer.WS_Items.SendItemInfo(ClientClass& client, Int32 item
ID) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Objects\WS.Items.vb:lin
e 534
   at mangosVB.WorldServer.WS_Items.On_CMSG_ITEM_QUERY_SINGLE(PacketClass& packe
t, ClientClass& client) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Obj
ects\WS.Items.vb:line 646
   at mangosVB.WorldServer.WS_Network.ClientClass.OnPacket(Object state) in C:\U
sers\Krill\Desktop\MVB\src\Server\WorldServer\Server\WS.Network.vb:line 387

**Comment by Kaev** [comment]
Any way to reproduce this problem?

**Comment by jaxx56** [comment]
Been to long, but IIRC it had trouble with querying items, and the items would show up as a Red ?
