### ISSUE TITLE
Packet Editing Cluster Crash

### ISSUE THREAD

**Issue by Krilliac** [mangosvb/serverZero#119]
Download a packet editor (WPE Pro, Packet Sender, Ect)

Type the Server Address and Port 8085 in their appropriate fields, then in the HEX field, put in 00 00 00 00

**[192.168.0.7:50947] OUT Packet: (0x01EC) SMSG_AUTH_CHALLENGE PacketSize = 4
|------------------------------------------------|----------------|
|00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F |0123456789ABCDEF|
|------------------------------------------------|----------------|
|00 00 00 00 |.... |**

is what displays by the server, followed by a crash with the following..

System.IndexOutOfRangeException: Index was outside the bounds of the array.
at WorldCluster.WC_Network.ClientClass.OnPacket(Object state) in C:\MVB\mangosvb\src\Server\WorldCluster\Server\WC.Network.vb:line 0
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Krilliac** [comment]
Fixed in f1d8467d8829256f9843998bca0a9f939cc6519f
