### ISSUE TITLE
Group invite client crash and opcode issues

### ISSUE THREAD

**Issue by Krilliac** [mangosvb/serverZero#128]
http://prntscr.com/lci2tv The Recipient client crashes when Party leader teleports/transfers to another continent 
http://prntscr.com/lci353 The Party Leader can transfer just fine

[08:36:34] Opcode handler CMSG_GROUP_UNINVITE:00000075 caused an error:
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at WorldCluster.Server.WC_Network.WorldServerClass.GroupSendUpdate(Int64 Grou
pID) in C:\MVB\mangosvb\src\Source\WorldCluster\Server\WC.Network.vb:line 489
   at WorldCluster.Handlers.WC_Handlers_Group.Group.Dispose(Boolean disposing) i
n C:\MVB\mangosvb\src\Source\WorldCluster\Handlers\WC.Handlers.Group.vb:line 96
   at WorldCluster.Handlers.WC_Handlers_Group.Group.Leave(CharacterObject& objCh
aracter) in C:\MVB\mangosvb\src\Source\WorldCluster\Handlers\WC.Handlers.Group.v
b:line 129
   at WorldCluster.Handlers.WC_Handlers_Group.On_CMSG_GROUP_UNINVITE(PacketClass
& packet, ClientClass& client) in C:\MVB\mangosvb\src\Source\WorldCluster\Handle
rs\WC.Handlers.Group.vb:line 522
   at WorldCluster.Server.WC_Network.ClientClass.OnPacket(Object state) in C:\MV
B\mangosvb\src\Source\WorldCluster\Server\WC.Network.vb:line 711

**Comment by Meltie2013** [comment]
Need to turn off my git bot

**Comment by Meltie2013** [comment]
New Crash on WC
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at WorldCluster.Server.WC_Network.ClientClass.SendMultiplyPackets(PacketClass& packet) in I:\Projects\Emulation\MangosVB Project\MangosVB\Source\WorldCluster\Server\WC.Network.vb:line 774
   at WorldCluster.Handlers.WC_Handlers_Group.Group.Broadcast(PacketClass& packet) in I:\Projects\Emulation\MangosVB Project\MangosVB\Source\WorldCluster\Handlers\WC.Handlers.Group.vb:line 283
   at WorldCluster.Handlers.WcHandlerCharacter.CharacterObject.Dispose(Boolean disposing) in I:\Projects\Emulation\MangosVB Project\MangosVB\Source\WorldCluster\Handlers\WC.Handlers.Character.vb:line 187
   at WorldCluster.Server.WC_Network.ClientClass.Dispose(Boolean disposing) in I:\Projects\Emulation\MangosVB Project\MangosVB\Source\WorldCluster\Server\WC.Network.vb:line 822
   at WorldCluster.Server.WC_Network.ClientClass.OnData(IAsyncResult ar) in I:\Projects\Emulation\MangosVB Project\MangosVB\Source\WorldCluster\Server\WC.Network.vb:line 680
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)```
