### ISSUE TITLE
WorldServer Crashing

### ISSUE THREAD

**Issue by jaxx56** [mangosvb/serverZero#75]
System.ApplicationException: Attempt to release mutex not owned by caller. (Exception from HRESULT: 0x00000120)
   at System.Threading.ReaderWriterLock.ReleaseReaderLockInternal()
   at mangosVB.WorldServer.WS_TimerBasedEvents.TSpellManager.Update(Object state) in C:\Users\Krill\Desktop\MVB\src\Server\WorldServer\Server\WS.TimerBasedEvents.vb:line 250
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

This is quite frequent and seems to be the leading cause of any WorldServer crash.

**Comment by jaxx56** [comment]
Seems to have been fixed in https://github.com/mangosvb/serverZero/commit/3a0619a8376f08f750493fe03531b631e8d490a7

Closing for now.
